<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_form-control pwd-in ng-untou_6c5235</name>
   <tag></tag>
   <elementGuidId>7fa30d35-97ac-4c8c-bbf3-867d2b2ba3cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control.pwd-in.ng-untouched.ng-dirty.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>46af5970-bc08-4718-8b0e-ffb296eaaabe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>2450fb72-3149-4bdc-a491-c49e20dba47f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your password</value>
      <webElementGuid>66def25b-ff70-4bce-abf2-1d44e4ef93d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>28ee8f32-f770-4472-a27a-238fa4de778b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>password-addon</value>
      <webElementGuid>a1f71579-50f2-480a-bc3c-cf8ec56a21a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control pwd-in ng-untouched ng-dirty ng-valid</value>
      <webElementGuid>983fee8c-cbfd-4088-9ea4-3b0839349002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>6cc235cf-0ecb-4540-a48a-470fb8c9e560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;remove-overflow&quot;]/app-root[1]/app-login[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;login_main&quot;]/div[1]/div[@class=&quot;d-flex w-100 overflow-hidden bg-white&quot;]/div[@class=&quot;login-form-sec align-self-center loginformscroll&quot;]/div[@class=&quot;login-right pt-5 my-md-4&quot;]/div[1]/form[@class=&quot;form-horizontal ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;mb-3 ng-star-inserted&quot;]/div[@class=&quot;input-group auth-pass-inputgroup&quot;]/input[@class=&quot;form-control pwd-in ng-untouched ng-dirty ng-valid&quot;]</value>
      <webElementGuid>b7edc7ad-42d3-4142-aae7-3477395a3b8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>3a28a72c-fd4e-46dd-9712-b0159565d9b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>2ca3fb60-6bb9-4595-b0aa-ff41ce606b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter your password' and @type = 'password']</value>
      <webElementGuid>615d8204-bed3-4646-aee6-faa2ec6bfb9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
